---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: Title
- type: textarea
  name: excerpt
  label: Excerpt
- type: text
  name: link
  label: Link to project
  config:
    required: true
pages:
- src/projects/here-is-a-test.md
